spring:
  datasource:
    url: jdbc:postgresql://137.184.247.91:5432/postgres
    username: postgres
    password: Iu2sJjLdEY
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    user:
      name: user
      password: password

server:
  port: 8090