spring:
  datasource:
    url: jdbc:postgresql://y-postgres-postgresql.default.svc.cluster.local/auth
    username: postgres
    password: QIUVH0GSzE
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    user:
      name: user
      password: password

server:
  port: 8090


